apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
# To create database with tables and raws:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS mydb;
    USE mydb;
    CREATE TABLE accounts (username VARCHAR(10), password VARCHAR(10), email VARCHAR(40));
  FLASK_APP: run.py
  MYSQL_ROOT_USER: root
  MYSQL_ROOT_PASSWORD: admin
  MYSQL_ROOT_HOST: "mysql-service.default.svc.cluster.local"
  MYSQL_ROOT_PORT: "3306"
  MYSQL_ROOT_DB: mydb
  FLASK_APP_PORT: "5000"